language: python
cache:
  - "pip"
python:
  - "3.6"
install:
  - "pip install coveralls"
  - "pip install -r requirements.txt"
script:
  - "nosetests --with-cover --cover-package=run"
after_success:
  - "coveralls"
