language: python
cache:
  - "pip"
  - "yarn"
python:
  - "3.6"
install:
  - "pip install pipenv"
  - "pipenv install --dev"
  - "pipenv run yarn install"
script:
  - "pipenv check"
  - "pipenv run prospector"
  - "pipenv run nose2 --with-coverage"
after_success:
  - "pipenv run coveralls"
