language: python
cache:
  - "pip"
  - "yarn"
python:
  - "3.6"
install:
  # Python Dependencies
  - "pip install pipenv"
  # Production Dependencies
  - "pipenv install"
  # Package Safety Check
  - "pipenv check"
  # Development Dependencies
  - "pipenv install --dev"
  # Node Dependencies
  - "nvm install --lts"
  - "nvm use --lts"
  - "pipenv run yarn install"
script:
  # Static Code Analysis
  - "PYTHONPATH=$(pwd) && pipenv run prospector"
  # Unit Tests
  - "pipenv run nose2 --with-coverage"
after_success:
  # Submit Coverage
  - "pipenv run coveralls"
deploy:
  skip_cleanup: true
  provider: script
  script: "pipenv run yarn deploy"
  on:
    branch: master
