language: python
cache:
  - "pip"
  - "yarn"
python:
  - "3.6"
install:
  # Python Dependencies
  - "pip install pipenv"
  # Production Dependencies
  - "pipenv install"
  # Package Safety Check
  - "pipenv check"
  # Development Dependencies
  - "pipenv install --dev"
script:
  # Static Code Analysis
  - "pipenv run prospector"
  # Unit Tests
  - "pipenv run nose2 --with-coverage"
after_success:
  # Submit Coverage
  - "pipenv run coveralls"
